spring.application.name=repo-analyzer
logging.level.org.hibernate.orm.jdbc.bind=WARN
logging.level.com.harshatha.repo_analyzer.service=DEBUG
logging.file.name=logs/repo-analyzer.log
logging.level.root=INFO
spring.servlet.multipart.max-file-size=500KB
spring.servlet.multipart.max-request-size=500KB
spring.jpa.properties.hibernate.jdbc.batch_size=50
spring.jpa.properties.hibernate.order_inserts=true