spring:
  application:
    name: repo-analyzer
  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME} 
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver
  jpa:
    hibernate:
      ddl-auto: update 
    show-sql: true
    properties:
      hibernate:
        format_sql: true
        order_inserts: true
        jdbc:
          batch_size: 50
  servlet:
    multipart:
      max-file-size: 500KB
      max-request-size: 500KB

logging:
  level:
    root: INFO
    org.hibernate.orm.jdbc.bind: WARN
    com.harshatha.repo_analyzer.service: DEBUG

application:
  security:
    jwt:
      secret-key: ${JWT_SECRET_KEY} 
      expiration: 86400000
  ai:
    gemini:
      api-key: ${GEMINI_API_KEY} 
      url: https://generativelanguage.googleapis.com/v1beta/models/gemini-2.5-flash:generateContent

groq:
  api:
    url: https://api.groq.com/openai/v1/chat/completions
    key: ${GROQ_API_KEY}

jina:
  api:
    key: ${JINA_API_KEY}

server:
  port: 8080
